### ISSUE TITLE
Documentation: Document Service/Agent/Executor Options via literalinclude of ConfigTemplate

### ISSUE THREAD

**Issue by andresailer** [DIRACGrid/DIRAC#4087]
Configuration options for agents or services should be documented. Default values are at the moment both present in ConfigTemplate.cfg files, and in the source code of the agent or service.

* Completeness and consistency of options between sourcecode and ConfigTemplate for agents is checked with ``ConfigurationSystem/test/Test_agentOptions.py`` (for services see #4079 )

* Options should be described in the docstring of the source code module, like it is done for the WorkflowTaskAgent for example:
https://github.com/DIRACGrid/DIRAC/blob/1e234f7737a553238facc44160c0c99a345326e4/TransformationSystem/Agent/WorkflowTaskAgent.py#L5-L9
https://github.com/DIRACGrid/DIRAC/blob/1e234f7737a553238facc44160c0c99a345326e4/TransformationSystem/ConfigTemplate.cfg#L67-L70
...
https://github.com/DIRACGrid/DIRAC/blob/1e234f7737a553238facc44160c0c99a345326e4/TransformationSystem/ConfigTemplate.cfg#L126-L127

* Files can be treated individually to avoid overloading PRs too much.
* At the same time information from  ``docs/source/AdministratorGuide/Configuration/ConfReference/Systems/`` should be removed. Information only present in the Administrator guide should be moved to the module docstring

These files selected by looking for files that do no include ```literalinclude```, some of these might not be agents or services, but utility files, in which case they should be ignored.

### Agents

- [x] AccountingSystem/Agent/NetworkAgent.py #4564 
- [x] ConfigurationSystem/Agent/Bdii2CSAgent.py #4520
- [x] ConfigurationSystem/Agent/GOCDB2CSAgent.py #4520
- [x] ConfigurationSystem/Agent/VOMS2CSAgent.py
- [ ] FrameworkSystem/Agent/CAUpdateAgent.py
- [x] FrameworkSystem/Agent/MyProxyRenewalAgent.py
- [x] RequestManagementSystem/Agent/CleanReqDBAgent.py  #4573 
- [x] RequestManagementSystem/Agent/RequestExecutingAgent.py  #4573
- [ ] StorageManagementSystem/Agent/RequestFinalizationAgent.py
- [ ] StorageManagementSystem/Agent/RequestPreparationAgent.py
- [x] StorageManagementSystem/Agent/StageMonitorAgent.py
- [ ] StorageManagementSystem/Agent/StageRequestAgent.py
- [x] TransformationSystem/Agent/InputDataAgent.py
- [x] TransformationSystem/Agent/MCExtensionAgent.py
- [x] TransformationSystem/Agent/RequestTaskAgent.py #4095 
- [x] TransformationSystem/Agent/TaskManagerAgentBase.py
- [x] TransformationSystem/Agent/TransformationAgent.py
- [x] TransformationSystem/Agent/TransformationPlugin.py
- [x] TransformationSystem/Agent/ValidateOutputDataAgent.py
- [ ] WorkloadManagementSystem/Agent/JobAgent.py
- [x] WorkloadManagementSystem/Agent/MultiProcessorSiteDirector.py
- [x] WorkloadManagementSystem/Agent/OptimizerModule.py
- [x] WorkloadManagementSystem/Agent/PilotStatusAgent.py
- [x] WorkloadManagementSystem/Agent/StalledJobAgent.py
- [x] WorkloadManagementSystem/Agent/StatesAccountingAgent.py

### Services

- [x] AccountingSystem/Service/DataStoreHandler.py  #4564 
- [x] AccountingSystem/Service/ReportGeneratorHandler.py  #4564 
- [x] ConfigurationSystem/Service/ConfigurationHandler.py   #4563 
- [ ] DataManagementSystem/Service/DataIntegrityHandler.py
- [ ] DataManagementSystem/Service/FileCatalogHandler.py
- [ ] DataManagementSystem/Service/FileCatalogProxyHandler.py
- [x] DataManagementSystem/Service/FTS3ManagerHandler.py
- [x] DataManagementSystem/Service/IRODSStorageElementHandler.py
- [ ] DataManagementSystem/Service/StorageElementProxyHandler.py
- [ ] FrameworkSystem/Service/BundleDeliveryHandler.py
- [ ] FrameworkSystem/Service/ComponentMonitoringHandler.py
- [ ] FrameworkSystem/Service/MonitoringHandler.py
- [ ] FrameworkSystem/Service/NotificationHandler.py
- [ ] FrameworkSystem/Service/PlottingHandler.py
- [x] FrameworkSystem/Service/ProxyManagerHandler.py
- [ ] FrameworkSystem/Service/RabbitMQSyncHandler.py
- [ ] FrameworkSystem/Service/SecurityLoggingHandler.py
- [ ] FrameworkSystem/Service/SystemAdministratorHandler.py
- [ ] FrameworkSystem/Service/SystemLoggingHandler.py
- [ ] FrameworkSystem/Service/SystemLoggingReportHandler.py
- [ ] FrameworkSystem/Service/UserProfileManagerHandler.py
- [x] MonitoringSystem/Service/MonitoringHandler.py
- [ ] ProductionSystem/Service/ProductionManagerHandler.py
- [x] RequestManagementSystem/Service/ReqManagerHandler.py    #4573
- [ ] RequestManagementSystem/Service/ReqProxyHandler.py
- [ ] ResourceStatusSystem/Service/PublisherHandler.py
- [ ] ResourceStatusSystem/Service/ResourceManagementHandler.py
- [ ] ResourceStatusSystem/Service/ResourceStatusHandler.py
- [ ] StorageManagementSystem/Service/StorageManagerHandler.py
- [ ] TransformationSystem/Service/TransformationManagerHandler.py
- [ ] WorkloadManagementSystem/Service/JobManagerHandler.py
- [ ] WorkloadManagementSystem/Service/JobMonitoringHandler.py
- [ ] WorkloadManagementSystem/Service/JobStateUpdateHandler.py
- [ ] WorkloadManagementSystem/Service/MatcherHandler.py
- [ ] WorkloadManagementSystem/Service/OptimizationMindHandler.py
- [x] WorkloadManagementSystem/Service/PilotManagerHandler.py
- [ ] WorkloadManagementSystem/Service/PilotsLoggingHandler.py
- [x] WorkloadManagementSystem/Service/SandboxStoreHandler.py
- [ ] WorkloadManagementSystem/Service/WMSAdministratorHandler.py

**Comment by kanishk16** [comment]
I just want to know if I am on the right track....So, just let me if something is incorrect...

> At the same time information from docs/source/AdministratorGuide/Configuration/ConfReference/Systems/ should be removed. Information only present in the Administrator guide should be moved to the module docstring

According to this, /docs/source/AdministratorGuide/Configuration/ConfReference/Systems/Transformation/Agents/transformationagent.rst is redundant and therefore needs to be removed after all the options are documented for agents and service files. 

Although the confusion lies in the part that isn't the docstring for the specific agent to be documented according to the code...

**Comment by andresailer** [comment]
I am not entirely sure I understand you question.

At the moment this rst file is not redundant as there is information in here

https://dirac.readthedocs.io/en/latest/AdministratorGuide/Configuration/ConfReference/Systems/Transformation/Agents/transformationagent.html
This is part of the AdministratorGuide

That is not present here:

https://dirac.readthedocs.io/en/integration/CodeDocumentation/TransformationSystem/Agent/TransformationAgent.html
This is not part of the AdministratorGuide, but of the CodeDocumentation, maybe not very clearly explained.

Once all the options for the agent are described (via ConfigTemplate.cfg and literalinclude), and the information about related options is added to the TransformationAgent.py module docstring, then the rst file in the ConfReference should be removed, and for the time being a reference to the CodeDocumentation entry can be added in the ConfReference page

In the end all the information for a given agent can be found in one place, and not scattered through too many pages. And we only have to document agent options once in the ConfigTemplate

> Although the confusion lies in the part that isn't the docstring for the specific agent to be documented according to the code...

I don't understand this phrase.

**Comment by kanishk16** [comment]
Now it's clear

**Comment by TaykYoku** [comment]
`FrameworkSystem/Service/ProxyManagerHandler.py` done with #4853

**Comment by fstagni** [comment]
I think most of them are done by now.
