### ISSUE TITLE
[JSON] What is missing to migrate from DEncode to JEncode

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#4320]
I will just use that as a master task to list all what is missing. 
Current status available on the jenkins instance (job "jsonSerialization")

Blocking
======

- [x] RSS ordering tuple https://github.com/DIRACGrid/DIRAC/issues/4321
- [x] StagingSystem https://github.com/DIRACGrid/DIRAC/issues/4322
- [x] Job Ids as index https://github.com/DIRACGrid/DIRAC/issues/4323
- [x] SecurityLogClient https://github.com/DIRACGrid/DIRAC/issues/4324
- [x] FrameworkMonitoring data https://github.com/DIRACGrid/DIRAC/issues/4326
- [x] RMS passes RequestIDs 
- [x] Plotters use int as keys https://github.com/DIRACGrid/DIRAC/issues/4328

Non blocking
==========

- [x] AccoutingDB https://github.com/DIRACGrid/DIRAC/issues/4319

Extract the logs
============

```
sed -n '/===================.*coding/,/===================/p' consoleText
```

Put one per file:

```
sed -n '/===================.*coding/,/===================/p' consoleText  | csplit - /====================================================================================================/ {*}
```

Analyze all the server log files

```
for s in $(ls //scratch/workspace/jsonSerialization/ServerInstallDIR/startup/); do echo $s; mkdir $s; cd $s; sed -n '/===================.*coding/,/===================/p' /scratch/workspace/jsonSerialization/ServerInstallDIR/startup/$s/log/current  | csplit - /====================================================================================================/ {*}; cd ..; done
```

Remove files only containing `==` lines

```
find . -type f -exec md5sum {} + | grep 4ef9e3f757edd4f96adb24d0a59893cd | awk {'print $2'} | xargs rm
```

Remove empty files

```
find . -type f -exec md5sum {} + | grep d41d8cd98f00b204e9800998ecf8427e | awk {'print $2'} | xargs rm
```

Remove files with the monitoring data
```
find . -type f -exec grep 'RunningThreads' {} + | awk -F ':' {'print $1'} | grep -v 'txt' | sort -u | xargs rm
```

Removing directory were there is nothing left

```
(ls; find . -name 'xx*' | awk -F '/' {'print $2'} | sort -u) | sort  | uniq -u | xargs rm -rf
```

And a bit of stats

```
grep -REn ' (De|En)coding ' . | awk -F '=============================================' {'print $2'} | sort | uniq -c 
```

HOW TO
=======

Basically there are two cases

* Dict with int as keys

You do not need to explicatly cast when you send, because the json lib is going to do it for you, but you can if you want, it's cleaner.. At least, put a comment

When you receive, you really have to cast back str to int. For that, there is a utility: 
`DIRAC.Core.Utilities.JEncode.strToIntDict` 

* Tuples

For tuples, the thing is that we do not really rely on tuples properties. So we may as well use lists. That's the preferred options. 
If you really do want to use tuple, then you have to cast back 

Also, since you will likely not be casting on the sending side (because JSON lib does it for you), you can suppress the warning by using `DIRAC.Core.Utilities.DEncode.ignoreEncodeWarning decorator` on the method that you know you took care of already

**Comment by fstagni** [comment]
Looks close-able to me.

**Comment by fstagni** [comment]
I think it can be closed.
